# Generated by Django 4.0.3 on 2022-05-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='categoria',
            field=models.ManyToManyField(to='blogapp.categoria'),
        ),
    ]
