# Generated by Django 4.0.3 on 2022-05-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_proveedor_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='subcategoria',
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
    ]
